---
id: es6-9
title: 9.비동기1
---
_[함수형 프로그래밍과 JavaScript ES6+](https://www.inflearn.com/course/functional-es6/dashboard)을 보고 학습한 내용을 정리한 것입니다._

- 비동기 사용방법
    - callback
    - Promise 기반
        - Promise method chain 통한 함수 합성
        - async/await

## callback과 Promise
- callback 이용한 코드
    - 100ms 이후에 동작하도록 한다.
    ```js
    function add10(a, callback) {
        //받아둔 함수를 실행해서 그 함수에 결과를 전달
        setTimeout(() => callback(a + 10), 100);
    }

    add10(5, res => {
        console.log(res);
    });
    // 10
    ```
- Promise 이용한 코드
    - callback 과 가장 큰 차이점은 Promise는 **Promise 객체를 반환**한다.
    - 100ms 이후에 동작하도록 한다.
        ```js
        function add20(a) {
            return new Promise(resolve => setTimeout(() => resolve(a + 20), 100));
        }

        add20(5)
            .then(console.log);  //25
        ```
        - 프로미스의 경우, 이 함수에서 사용할 인자를 하나만 받는다.
        - add20 은 프로미스를 만들어서 리턴해준다. 또한 then 메서드를 통해 내부의 값을 꺼내어 사용한다.

- 연속적인 실행
    ```js
    //콜백을 통한 연속적인 실행
    add10(5, res => {
        add10(res, res => {
            add10(res, res => {
                console.log(res);
            });
        });
    });

    //프로미스를 통한 연속적인 실행의 경우, then만 작성해주면 된다.
    add20(5)
        .then(add20)
        .then(add20)
        .then(console.log);
    ```

## 비동기를 값으로 만드는 Promise
- Promise와 callback 함수 차이   
    - Promise는 **일급으로 비동기 상황을 다룬다**는 점이 가장 중요한 차이를 가진다. 
        - 프로미스라는 클래스를 통해서 만들어진 인스턴스를 반환한다. 반환된 프로미스 값은 대기, 성공, 실패를 다루는 일급 값으로 이루어진다.
        - 코드로만 표현되는 것이 아닌 비동기 상황에 대한 값을 만든다.
    
    - 코드로 보기
        ```js
        var a = add10(5, res => {
            add10(res, res => {
                add10(res, res => {
                    console.log(res);
                });
            });
        });

        console.log(a);  //undefined

        var b = add20(5)
            .then(add20)
            .then(add20)
            .then(console.log);

        console.log(b);  //Promise { }

        add10(5, _ => _);  //undefined
        add20(5, _ => _);  //Promise { }

        var c = add20(5, _ => _);
        console.log(c); //Promise { }
        var d = c.then(a => a - 5);
        console.log(d); //Promise { }
        ```
        - callback : add10 은 실행 후 어떠한 일도 할 수 없다. **undefined를 반환**한다.
        - Promise : add20 은 실행 후 이후에 **추가적인 일**도 할 수 있다. **Promise를 반환**하기 때문.
            - 비동기로 일어난 상황에 대해서 값으로 다룰 수 있고 값으로 다룰 수 있다는 것은 일급이라는 의미이다.
            - 일급이라는 것은 어떤 변수에 할당될 수 있고, 어떤 함수에 전달될 수 있고, 전달된 값으로 또 다른 일을 이어나갈 수 있다.

## 값으로서의 Promise 활용
- Promise 일급 성질로 다양한 처리가 가능하다.
- 아래의 코드가 실행되기 위한 조건으로 a, f (인자) 모두 동기적이어야 한다.
    - 바로 값을 알 수 있어야 한다. 즉, 프로미스가 아닌 값이 들어와야 한다.
    ```js
    const go1 = (a,f) => f(a);
    const add5 = a => a + 5;
    go1(10, add5);
    ```
    - 만약 프로미스 값이 들어간다면 정상적인 연산이 안된다.
    - 프로미스 값이 들어와도 정상적으로 연산하게 만들기
        ```js
        //delay100 을 Promise로
        const delay100 = a => new Promise(resolve =>
            setTimeout(() => resolve(a), 100));
        
        //promise 라도 정상적인 동작이 되도록 만든다.
        //promise라면 a.then(f)
        const go1 = (a, f) => a instanceof Promise ? a.then(f) : f(a);
        const add5 = a => a + 5;

        var r = go1(10, add5);  //15
        console.log(r);

        var r2 = go1(delay100(10), add5);
        //console.log(go1(delay100(10), add5));  //Promise { }
        r2.then(console.log);  //15
        ```
        - delay100 는 들어온 값을 100ms 뒤에 받아둔 값을 그대로 리턴해주는 함수이다. 
        - go1 함수를 Promise가 일급이라는 성질을 이용해서 비동기 상황인지를 체크한다.
            - 넘어온 인자 a 가 Promise 이면 a.then(f)를, 아니면 f(a) 를 한다.
            - 즉, 둘 다 a+5 를 수행한다. 
            - go1 함수는 다형성을 지원한다.

## 합성 관점에서의 Promise와 모나드
- 모나드
    - Promise는 비동기 상황에서 함수 합성을 안전하게 하기 위한 모나드 이다.
    - 함수 합성을 안전하게 하기 위한 도구이다.
    - **컨테이너에 값이 들어있고 그 값을 통해서 함수 합성을 안전하게 해나가는 것**이다.
    - 예시 코드
        - 인자 값을 받아 1을 더해주는 g라는 함수와 인자 값을 제곱해 반환하는 함수 f
        ```js
        const g = a => a+1;
        const f = a => a*a;
        log(f(g(1)));   //4
        log(f(g()));  //NaN
        ```
        - `log(f(g()));`
            - NaN 가 출력된다. 비정상적인 동작을 했다는 것이다.
            - 함수 합성에 사용되는 인자값이 유의미한 값이 아니여서 발생하는 문제이다.
            - 위와 같이 인자값으로 어떤 값이 올 지 모르고 빈 값이 올 수도 있다.
            - 즉, f(g(x)) 합성함수는 안전하지 않은 합성함수라고 할 수 있다. 
            - 위와 같이 **인지값으로 어떤 값이 올 지 모르는 불안한 상황에서 함수 합성을 어떻게 안전하게 할 지 고려**하며 나온 것이 `모나드` 이다.

        - 위의 코드를 모나드로 표현
            ```js
            log([1].map(g).map(f));  // [4]
            ```
            - 모나드는 박스를 가지고 있고 그 내부의 실제 효과나 연산에 필요한 재료들을 가지고 있고 이를 통해 함수 합성을 한다.
                - [1] : 박스 안의 재료는 1
            - 반환값이 Array이고 최종 유효값으로 볼 수는 없다. 그렇기 때문에 Array 안에 있는 최종 값을 꺼내야 한다.<br/><br/>
                ```js
                [1].map(g).map(f).forEach(r => console.log(r));  // 4
                ```
                - `log(f(g(1)));` 와 동일

        - 모나드를 통한 함수 합성의 이점
            ```js
            [1].map(g).map(f).forEach(r=>log(r));  // 4
            [].map(g).map(f).forEach(r=>log(r));  // 결과 없음
            ```
            - 박스 안에 효과가 있는지 없는지에 따라서 함수 합성을 안전하게 하고 있다는 의미이다.
            - log(f(g())); 의 경우 빈 값이 들어와도 빈 값을 나타내는 효과까지 가는데, 모나드 방식을 사용하면 안전하게 효과를 아예 일으키지 않는 식으로 작동한다. => 안전하게 함수 합성 
                - 위의 [ ] 은 유효하지 않은 값이 들어와 결과가 없다.
- Promise
    - 모나드와 동일한 방식으로 구현된다.
    ```js
    //Array 함수 합성
    Array.of(1).map(g).map(f).forEach(r => console.log(r));   // 4
 
    Promise.resolve(1).then(g).then(f).then(r => console.log(r));  //4
    ```
    - Promise 는 then() 을 통해서 함수 합성을 한다.
    - Promise 는 안에 값이 있거나 없거나에 대한 안전한 합성을 하기 위한 것은 아니고 **비동기 상황을 안전하게 합성하기 위한 도구**이다.
    - 비동기 상황이란, 얼마만큼 지연이 필요한 상황에서도 함수를 적절한 시점에 평가해서 합성 시키기 위한 도구이다.
    

## Kleisli Composition 관점에서의 Promise
- Promise는 Kleisli Composition을 지원하는 도구이다.
- 함수 합성 방법은 오류가 있을 수 있는 상황에서의 함수합성을 안전하게 하는 하나의 규칙이라고 볼 수 있다.
- 그러나 함수합성이 원하는대로 되지 않을 가능성이 있다.
- Kleisli Composition 은 들어오는 인자가 잘못되어 함수에서 오류가 나거나 정확한 인자가 들어왔더라도 특정 함수가 의존하는 외부의 상태에 의해 결과를 정확히 전달하기 힘든 상황에서 `에러가 나는 것을 해결하기 위한 함수 합성`이라고 볼 수 있다.

- 예시 코드
    ```js
    var users = [
        { id: 1, nmae: 'aa' },
        { id: 2, name: 'bb' },
        { id: 3, name: 'cc' }
    ];

    const getUserById = id =>
        find(u => u.id == id, users);

    const f = ({ name }) => name;
    const g = getUserById;
    const fg = id => f(g(id));

    console.log(fg(2));   // bb
    console.log(fg(2) == fg(2));  // true
    ```
    - f(g(2)) 는 users 에서 id 값이 2인 것을 찾아서 이름을 출력하는 함수합성 이다.
    - fg(2) == fg(2) 는 당연히 true 가 나온다.
    - 하지만, 실세계에선 data(users)의 변화가 생긴다.
        ```js
        const r = fg(2);
        console.log(r);   //bb

        users.pop();
        users.pop();

        const r2 = fg(2);
        console.log(r2);  //error
        ```
        - users.pop() 에 의해 data의 변화가 발생했다.
            - pop() 이후의 id=2 의 값이 제거 되었다.
        - 변화 이후 출력을 해보면 `error` 가 난다. 
            - 즉 fg(2) == fg(2) 가 성립되지 못한다.
            - 외부의 변화가 일어난다면 안전한 합성을 할 수 없다.
        - 이렇게 합성을 하면서 **에러가 나지 않게 하는게 Kleisli Composition** 이다.         
    
    - 에러나지 않도록 코드 변경
        - getUserById 에 Promise.reject('없어요!') 추가
        - 함수 합성 코드를 Promise로 변경 (const fg)
        ```js
        const getUserById = id =>
            find(u => u.id == id, users) || Promise.reject('없어요!');

        const f = ({ name }) => name;
        const g = getUserById;

        //아래가 코드변경
        const fg = id => Promise.resolve(id).then(g).then(f).catch(a => a);

        users.pop();
        users.pop();

        //pop된 후 실행하면 에러가 발생한다.
        fg(2).then(console.log);
        ```
        - users.pop() 을 하기 전 결과는 bb 이다.
        - pop() 이후 결과는 기존에 error 가 났다면 이제는 `없어요!` 가 출력된다.
        - `Promise.reject('없어요!')` 
            - Promise 결과를 찾아봤을 때 결과가 없으면 Promise.reject 값을 리턴한다.
        - Promise.resolve(id).then(~) 이 코드 대신 f(g(2)) 를 실행하면 `undefined` 가 출력된다.
        - 위와 같이 엉뚱한 결과를 받아들이지 않고 로그도 출력되지 않는다. 로그에 출력되는 값은 Promise.rejcet에 정해준 값이 나오게 된다.

## go, pipe, reduce 에서 비동기 처리
- go, pipe, reduce 함수는 어떠한 함수를 연속적으로 실행하는 함수 합성에 대한 함수들이다.
- Promise의 비동기를 값으로 다루는 성질을 이용해서 비동기 상황에서 잘 대응하도록, Kleisli Composition 처럼 중간에 reject나 error 가 발생했을 때 대기 중인 이후 함수들을 실행시키지 않는 등 기법들을 적용할 수 있다.
- 코드
    ```js
    const reduce = curry((f, acc, iter) => {
        if (!iter) {
            iter = acc[Symbol.iterator]();
            acc = iter.next().value;
        } else {
            iter = iter[Symbol.iterator]();
        }
        let cur;
        while (!(cur = iter.next()).done) {
            const a = cur.value;
            acc = f(acc, a);
        }
        return acc;
    })

    const go = (...args) => reduce((a, f) => f(a), args);

    go(1,
        a=>a+10,
        a=>Promise.resolve(a+100),
        a=>a+1000,
        a=>a+10000,
        console.log);
    ```
    - 비동기 상황이 일어나서 Promise 를 리턴하는 함수가 합성되면 비정상적인 동작이 일어난다.

    - 올바른 동작 일어나는 코드 생성하기
        - **첫번째** 방법 => 조금 부족!
            - go 함수의 제어권은 reduce가 가지고 있기 때문에 reduce 코드의 변경이 필요하다.
            - `a => Promise.resolve(a + 100)` 코드를 통해 reduce 의 acc가 Promise가 된다. 그 이후 프로미스를 전달한 채로 함수가 실행되기 때문에 프로미스의 값을 기다려서 만들어진 값으로 변환을 해주어야 연속적으로 실행이 가능해 진다.

            ```js
            const reduce = curry((f, acc, iter) => {
                if (!iter) {
                    iter = acc[Symbol.iterator]();
                    acc = iter.next().value;
                } else {
                    iter = iter[Symbol.iterator]();
                }
                let cur;
                while (!(cur = iter.next()).done) {
                    const a = cur.value;
                    //acc = f(acc, a);
                    acc = acc instanceof Promise ? acc.then(acc => f(acc, a)) : f(acc, a);
                }
                return acc;
            });
            ```
            - 함수가 중간에 Promise를 만나게되면 그 뒤로는 계속해서 Promise Chaning이 걸리게 된다.
                - 즉, a => Promise.resolve(a + 100) 이후의 코드인 a => a + 1000 도 Promise로 동작한다.
            - Promise 가 된 이후 실행 함수에서는 동기적으로 즉시평가를 하고 싶은 경우에는 올바른 코드가 아니다.

        - **두번째** 방법 => 재귀를 사용
            ```js
            const reduce = curry((f, acc, iter) => {
                if (!iter) {
                    iter = acc[Symbol.iterator]();
                    acc = iter.next().value;
                }
                //유명함수 이용한 재귀
                return function recur(acc) {
                    let cur;
                    while(!(cur = iter.next()).done) {
                        const a = cur.value;
                        acc = f(acc, a);
                        if(acc instanceof Promise) return acc.then(recur);
                    }
                    return acc;
                }(acc);
            });

           go(1,
            a=>a+10,
            a=>Promise.resolve(a+100),
            a=>a+1000,
            a=>a+10000,
            console.log);  //11111
            ```
            - 유명함수를 이용해 재귀를 구현한다.
            - 처음 a => a+10 은 Promise가 아니기 때문에 acc = 11이 되고 while문으로 이동한다. 그 다음 a => Promise.resolve(a+100) 는 Promise 이기 때문에 acc.then(recur) 를 통해 recur 함수로 다시 들어가게 되고 이때 recur 함수의 인자로 들어가는 acc 는 a+100 이 들어가게 된다. 따라서, acc = 111 이 되고 나머지 함수들은 Promise가 아니기 때문에 while문에서 처리가 된다. 
            - 더 효율적으로 동작한다.
        
        - 상황 1 => 첫 번째 인자로 들어가는 인자가 Promise인 경우도 처리
            - 위의 재귀 형태에서의 reduce일 때, 첫 번째 인자로 Promise를 넘겨주면 처음 시작하는 acc 자체가 Promise 이기 때문에 제대로 된 결과가 나오지 않는다.
            ```js
            go(Promise.resolve(1),
                a => a + 10,
                a => Promise.resolve(a + 100),
                a => a + 10000,
                console.log
            );  //[object Promise]10100100010000
            ``` 
            - 위의 문제를 해결하기 위해서는 첫 번째 인자가 Promise 인지 아닌지를 판단하여 Promise인 경우 then을 통해 전달해야 한다. -> go1 함수 적용
            ```js
            const go1 = (a,f) => a instanceof Promise ? a.then(f) : f(a);

                ...
                return go1(acc, function recur(acc) {
                    let cur;
                    while (!(cur = iter.next()).done) {
                        const a = cur.value;
                        acc = f(acc,a);
                        if (acc instanceof Promise) return acc.then(recur);
                    }
                    return acc;   
                });
            });
            ```
        - 상황 2 => 중간의 인자값 함수가 Promise.reject('error') 인 경우
            ```js
            go(Promise.resolve(1),
                a=>a+10,
                a=>Promise.reject('error'),
                a=>log('----'),
                a=>a+1000,
                log
            ).catch(a=>log(a));  //error~
            ```
            - catch 문이 없으면 `a=>Promise.reject('error')` 코드 이후의 코드는 실행되지 않고 error 가 발생한다.
            - reject 가 발생하여 실패했을 때를 위해 catch문을 작성해 주어야 한다.
- 결론
    - 합성 함수의 초기값 혹은 중간 값으로 Promise를 받거나 수행할 경우에도 정상적으로 동작할 수 있게 되었다. go,pipe,reduce 와 같은 함수에서 중간에 Promise를 만났을 때 다형적으로 대응해 줄 수 있고 함수합성이 더 안전하게 된다. **값으로 Promise를 다룸**으로써 가능해졌다. then을 실행하여 콜백지옥을 해결 용도로만이 아닌 원하는 시점에서 원하는 동작을 할 수 있는 고차함수를 만드는 등의 응용을 다양하게 할 수 있다.


## promise.then의 중요한 규칙
- 아무리 많은 Promise의 중첩으로 구성되어 있어도 단 하나의 then을 통해 값을 꺼내 쓸 수 있다는 규칙이다.
- 가장 내부의 있는 값이 도출된다.
```js
Promise.resolve(Promise.resolve(1)).then(log);  //1
new Promise(resolve => resolve(new Promise(resolve1 => resolve1(1)))).then(log);//1
```
- 